name: Say helllo
on:
    push:
        branches: 
            - main

jobs:
    hello_world:
        runs-on: ubuntu-18.04
        steps:
            - name: Echo message
              run: |
                echo "Hello world"